[versions]
# libraries

# plugins
kotlin = "1.8.21"
intellijPlatform = "2.5.0"

[plugins]
intellijPlatformPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform"}
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
